// generate-dive-log: Creates an AI-generated dive log from processed highlights

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

Deno.serve(async (req) => {
  try {
    const { diveId, userId } = await req.json()

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    )

    // Fetch dive details
    const { data: dive } = await supabase
      .from('dives')
      .select('*')
      .eq('id', diveId)
      .single()

    if (!dive) {
      return new Response(JSON.stringify({ error: 'Dive not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Fetch highlights with species
    const { data: highlights } = await supabase
      .from('highlights')
      .select('*, highlight_species(*, species(*))')
      .eq('dive_id', diveId)
      .order('start_time')

    // Build species seen list
    const speciesMap = new Map<string, { name: string; count: number; first_seen: string; confidence: number }>()

    for (const h of highlights ?? []) {
      for (const hs of (h as { highlight_species: Array<{ species: { common_name: string }; confidence: number }> }).highlight_species ?? []) {
        const name = hs.species?.common_name
        if (!name) continue
        const existing = speciesMap.get(name)
        if (existing) {
          existing.count++
          existing.confidence = Math.max(existing.confidence, hs.confidence)
        } else {
          const mins = Math.floor(h.start_time / 60)
          const secs = Math.floor(h.start_time % 60)
          speciesMap.set(name, {
            name,
            count: 1,
            first_seen: `${mins}:${secs.toString().padStart(2, '0')}`,
            confidence: hs.confidence,
          })
        }
      }
    }

    const speciesSeen = Array.from(speciesMap.values())

    // Generate narrative summary (mock template)
    const durationMins = dive.duration ? Math.round(dive.duration / 60) : null
    const speciesNames = speciesSeen.map((s) => s.name)
    const highlightCount = highlights?.length ?? 0

    let summary = ''
    if (durationMins) {
      summary += `${durationMins}-minute dive`
    } else {
      summary += 'Dive'
    }
    if (dive.location_name) {
      summary += ` at ${dive.location_name}`
    }
    summary += `. `

    if (dive.max_depth) {
      summary += `Maximum depth reached was ${dive.max_depth} meters`
      if (dive.visibility) {
        summary += ` with ${dive.visibility}m visibility`
      }
      summary += '. '
    }

    if (speciesNames.length > 0) {
      summary += `During this dive, ${speciesNames.length} species were identified: ${speciesNames.join(', ')}. `
    }

    if (highlightCount > 0) {
      summary += `The AI pipeline extracted ${highlightCount} highlights from the footage. `
    }

    if (speciesSeen.length > 0) {
      const topSpecies = speciesSeen.sort((a, b) => b.confidence - a.confidence)[0]
      summary += `The most notable encounter was a ${topSpecies.name} first spotted at the ${topSpecies.first_seen} mark with ${Math.round(topSpecies.confidence * 100)}% confidence. `
    }

    if (dive.water_temp) {
      summary += `Water temperature was ${dive.water_temp}°C. `
    }

    summary += 'This dive log was automatically generated by DiveApp AI.'

    // Build conditions
    const conditions: Record<string, string> = {}
    if (dive.water_temp) conditions.water_temperature = `${dive.water_temp}°C`
    if (dive.visibility) conditions.visibility = `${dive.visibility}m`
    if (dive.max_depth) conditions.max_depth = `${dive.max_depth}m`
    if (durationMins) conditions.duration = `${durationMins} minutes`

    // Upsert dive log
    const { error } = await supabase
      .from('dive_logs')
      .upsert({
        dive_id: diveId,
        user_id: userId,
        summary,
        species_seen: speciesSeen,
        conditions,
        ai_generated: true,
      }, { onConflict: 'dive_id' })

    if (error) {
      console.error('Failed to create dive log:', error)
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    return new Response(
      JSON.stringify({ message: `Dive log created for dive ${diveId}` }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    )
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }
})
